### ISSUE TITLE
Make colors easily configurable for red-green color-deficient users

### ISSUE THREAD

**Issue by crossroads1112** [jeffkaufman/icdiff#110]
Hello! I work with @CS50 (Harvard's introductory computer science course) and we just rolled out a new version of our style checking tool which uses `icdiff` for one of its output modes. Thanks for making such a great tool!

We've received requests from color-deficient students to make the colors configurable, and though this seems feasible with `icdiff` as it currently stands (by modifying `icdiff.color_codes` directly), it would be nice if there were a way to more-easily configure this.

Our tracking issue: https://github.com/cs50/style50/issues/19

Thanks again!

**Comment by jeffkaufman** [comment]
Responded on https://github.com/cs50/style50/issues/19#issuecomment-322001964

Please reopen this issue if you still think I should change something here.
