### ISSUE TITLE
Indentation on changed lines with \r ending

### ISSUE THREAD

**Issue by mqudsi** [jeffkaufman/icdiff#111]
_Creating this as a separate issue from our other discussion_

Running the latest `master` version of the code, lines that are _changed_ and have a `\r` line ending are shown indented, vs lines that were added with a `\r` line ending which are shown just fine.

I've attached the two files I'm diffing and a screenshot of the default `icdiff` output in the comparison between them:

![icdiff](https://user-images.githubusercontent.com/606923/29430246-5e03d9c2-8359-11e7-9112-6c939685ede2.png)

[bcd.txt](https://github.com/jeffkaufman/icdiff/files/1232395/bcd.txt)
[bcd.txt](https://github.com/jeffkaufman/icdiff/files/1232396/bcd.txt)

**Comment by jeffkaufman** [comment]
Thanks for the report!  Fixed!
