### ISSUE TITLE
Pathological case takes 45 seconds to compare two files

### ISSUE THREAD

**Issue by mqudsi** [jeffkaufman/icdiff#112]
I have a php source file that was reformatted with `phptidy`; `diff` compares the two in too little time to show up as anything other than `0.00` with `time`, but `icdiff` takes `42.67 real 42.61 user 0.05 sys`. (running git master 0e3a4cf259d53b609733e8c1812890b85e185ccc)

If it's just a matter of `icdiff` doing a lot more work and the chunk-finding algorithm being very computationally intensive then it is is what it is, but in case it really shouldn't be taking this long to compare the files I figured I'd share them with you here.

When comparing, `icdiff` spews out a chunk of differences, then hangs for a while, then spews out some more, repeating the process until it's done.

* File 1: http://termbin.com/0alz (MD5 (file1) = d7663981c29580197b5df7ad9a01a03b)
* File 2: http://termbin.com/44sc (MD5 (file2) = 35cd9b162a707a50db33d957a3c670cf)

**Comment by mqudsi** [comment]
Interesting. Normalizing the line endings (`unix2dos file1 file2`) results in `icdiff` completing in 2.67 seconds instead.

**Comment by jeffkaufman** [comment]
You could try with `--strip-trailing-cr`

Ultimately, this is an issue with [difflib](https://docs.python.org/2/library/difflib.html), since icdiff is just a pretty wrapper around that

**Comment by mqudsi** [comment]
Bugged here: https://bugs.python.org/issue31561
