### ISSUE TITLE
I have some problem about "git difftool --extcmd icdiff" in window7.

### ISSUE THREAD

**Issue by Guang1234567** [jeffkaufman/icdiff#116]
Hello @jeffkaufman 

I have some problem about the usage of   "git difftool --extcmd icdiff" in window7,   help me please.
----
**Details:** 

**Python Version 2.7**

![20171113113112](https://user-images.githubusercontent.com/8240718/32708659-334803be-c866-11e7-916d-acd66685e3fd.png)

---
Error output:

**error: file 'E:/Users/LIHANG~1/AppData/Local/Temp/xIoQFb_RichMessageHandler.java' not valid with encoding 'utf-8': <invalid continuation byte> at 4-5.**

**Comment by jeffkaufman** [comment]
What encoding is the file in?  `icdiff` doesn't auto-detect encodings: it assumes utf8.  If you're using something else you need to pass that in with `--encoding=`.  I don't think `git difftool --extcmd` offers a way to pass arguments to the external diffcmd, so you'd have to use a script.

**Comment by jeffkaufman** [comment]
(See also https://github.com/jeffkaufman/icdiff/issues/65)

**Comment by Guang1234567** [comment]
@jeffkaufman 

Thanks your reply. `The file's encoding is UTF-8.`
