### ISSUE TITLE
Option to change dark blue color in the diff

### ISSUE THREAD

**Issue by vaygr** [jeffkaufman/icdiff#117]
With black terminal background it's really hard to see file names and `---` separators in dark blue.

It'd be great to be able to switch it to something else with a flag. Like white?

**Comment by jeffkaufman** [comment]
If you don't like the color your terminal uses for dark blue, would it work for you to change your terminal's color settings? This will work for all programs, not just icdiff.

**Comment by vaygr** [comment]
I thought about that, but for programs like tig or newsbeuter/newsboat it fits the view just right, i.e. when it's a background for the text, not the text itself.

**Comment by jeffkaufman** [comment]
Ok, I've added this now in 82c59e0.  You can say:

    icdiff a b --color-map=separator:white,description:white

If this works for you I'll make a release.

**Comment by vaygr** [comment]
This is fantastic, thanks a lot. Works like a charm, just tested it.
