### ISSUE TITLE
An option to ignore all whitespaces?

### ISSUE THREAD

**Issue by sgon00** [jeffkaufman/icdiff#118]
Can we have an option to ignore all whitespaces just like `diff -w` ?
Thanks a lot.

**Comment by jeffkaufman** [comment]
Sounds like a useful feature!  It's ok with me if someone wants to add this, but I'm not up for adding it right now.

**Comment by ViktorQvarfordt** [comment]
I would very much like to have this feature!

@jeffkaufman Do you think it would it be possible to use the option `--ignore-space-change` to `git diff`? https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---ignore-space-change

**Comment by ViktorQvarfordt** [comment]
More generally, it would be nice if one can simply use the underlying git diff strategy and corresponding configurations in the case of `git` + `icdiff` integration. I observe some differences between `git diff` and `git icdiff`
