### ISSUE TITLE
Feature Request: Add bold to the highlighted characters (icdiff -H a b).

### ISSUE THREAD

**Issue by babam86** [jeffkaufman/icdiff#122]
Hi, 

Add bold to the highlighted characters (icdiff -H a b). 

Thanks.

**Comment by jeffkaufman** [comment]
Fixed!

This changes behavior when showing highlighted text: before the bold attribute would be dropped by highlighting.  I think this is a bug, so I changed things in 031573c so that the bold attribute would be preserved.  For people who prefer the old behavior the fix is to use:

    icdiff a.txt b.txt --highlight --color-map='add:green,subtract:red,change:yellow'

Or just:

    icdiff a.txt b.txt --highlight --no-bold
