### ISSUE TITLE
Feature Request: Add the ability to change the color of the highlighted character/text to white.

### ISSUE THREAD

**Issue by babam86** [jeffkaufman/icdiff#123]
Hi, 

Add the ability to change the color of the highlighted character/text to white. 

Thanks.

**Comment by jeffkaufman** [comment]
Right now highlighting is just done with code `7` for "reverse video".  This means the foreground color will be the same as the terminal background.

We could switch from reverse video to explicitly setting the foreground and background color, but that would be annoying and I'm not sure it's worth it.

**Comment by babam86** [comment]
Foreground color and background color is not the same. 

Example: 
Foreground = white 
Background = black 
Highlight = red
