### ISSUE TITLE
git-icdiff doesn't work once icdiff.options set

### ISSUE THREAD

**Issue by ptthisdan** [jeffkaufman/icdiff#125]
Bash Version:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
Git Version: 2.15.1

Have to change the last line of git-icdiff to:
`git difftool --no-prompt --extcmd="icdiff $ICDIFF_OPTIONS" "$@" | $GITPAGER`

or the command git icdiff won't work once icdiff.options set in git config

**Comment by vaygr** [comment]
@ptthisdan I believe support for it was added [recently](https://github.com/jeffkaufman/icdiff/pull/115) right after **1.9.1** release, and **1.9.2** is not out yet.

**Comment by jeffkaufman** [comment]
v1.9.2 is out now; if you use that it should work
