### ISSUE TITLE
Output file options

### ISSUE THREAD

**Issue by jrjhealey** [jeffkaufman/icdiff#126]
Hi Jeff,

Not an issue, but maybe a feature request, if the package doesn't already do this?

I'd like to output the differences between 2 files in 'order of severity'. For example, if a whole line has changed, I'd like to put those differences in to a new file, but ignore lines where maybe just a single character or some whitespace has changed.

Alternatively, outputting the whole STDOUT would be an option, if there is some mechanism of preserving the colouration in other applications?

Many thanks (and love the program otherwise!),

Joe

**Comment by jeffkaufman** [comment]
> outputting the whole STDOUT would be an option, if there is some mechanism of preserving the colouration in other applications?

icdiff colors the output by inserting [ECMA-48 color codes](https://en.wikipedia.org/wiki/ANSI_escape_code).  Piping icdiff output into other programs should preserve the coloration fine?

**Comment by jrjhealey** [comment]
After experimenting, (e.g. `icdiff file1 file2 > mydiffs.txt`) the `mydiffs.txt` file preserves the colour in my terminal/shell if I subsequently `cat` the file for instance. That leaves my other query about parsing out the differences 'by severity'? My initial thoughts, if I have to hack this together myself, would be to grep for the various colour codes in the absence of a specific icdiff functionality?

I'm wondering if you know of a 3rd party tool like TextEdit or TextWrangler which will interpret the escape characters/colours like the shell does?

**Comment by jrjhealey** [comment]
Ah that might be a neater solution in the end yeah. I'll look into it thanks!

Feel free to close this issue, unless you want to keep the feature request open for parsing out the lines!

Thanks,

Joe
