### ISSUE TITLE
Line matching algorithm

### ISSUE THREAD

**Issue by IngoHeimbach** [jeffkaufman/icdiff#127]
Hey, thanks for `icdiff`, I use it every day. 👍 
I have noticed that `icdiff` sometimes matches like this:
![image](https://user-images.githubusercontent.com/1449087/36386104-f00cf4b6-1594-11e8-98f9-18d8f1570b1b.png)
Wouldn't it be better if the second `pass` was shown in green? I do not quite understand why the first `pass` is detected as a new line.

**Comment by jeffkaufman** [comment]
I agree that would be better!

Unfortunately `icdiff` is just a wrapper around python's `difflib`, and this happens inside `difflib`
