### ISSUE TITLE
icdiff gets messed up in diff compared to standard diff

### ISSUE THREAD

**Issue by edi9999** [jeffkaufman/icdiff#128]
I use icdiff in my tools to do comparison of files, and it always worked well (until right now)

Here are two files I'm trying to compare : 

[f2.txt](https://github.com/jeffkaufman/icdiff/files/1799168/f2.txt)
[f1.txt](https://github.com/jeffkaufman/icdiff/files/1799169/f1.txt)

If I run 

    icdiff f1.txt f2.txt

I get a big output : 

![selection_004](https://user-images.githubusercontent.com/2071336/37239597-2185dff4-243f-11e8-8704-ae9f54c4b384.png)

However, between f1 and f2, the only thing that change is that some `<w:t>` have been replaced by `<w:t xml:space="preserve">` as you can see if you run : 

    diff f1.txt f2.txt

![selection_005](https://user-images.githubusercontent.com/2071336/37239605-53cb7622-243f-11e8-82a7-e4a92c0af33b.png)

Do you know why icdiff thinks there is such a big diff and if this is fixable ?

**Comment by jeffkaufman** [comment]
icdiff is just a wrapper around Python's difflib, and almost all issues like this are upstream problems.

Sorry!

**Comment by edi9999** [comment]
Can you open that issue for me ? 

```
diffs = difflib._mdiff(fromlines, tolines, context_lines,
                               linejunk=self._linejunk,
                               charjunk=self._charjunk)
```

I see that you do this in your code, but not sure how to make a reproducible example for upstream ...
