### ISSUE TITLE
Feature Request: Syntax Highlighting

### ISSUE THREAD

**Issue by madnight** [jeffkaufman/icdiff#133]
Maybe you could use http://pygments.org/docs/cmdline/

Or something that looks like this https://github.com/sharkdp/bat
![Syntax highlighting example](https://imgur.com/rGsdnDe.png)

**Comment by jeffkaufman** [comment]
Looking at the delta and icdiff codebases, I think delta is probably a better place for this feature.

**Comment by bvaughn** [comment]
> I don't see how to keep the colors from diffing and the colors from syntax highlighting from interfering.

Totally respect your stance on not wanting to implement this. I imagine it could be a lot of work.

But I am curious if you considered using background color for diffing and foreground color for syntax highlighting (similar to what GitHub does)?

**Comment by jeffkaufman** [comment]
Delta has now implemented this, so I don't think it makes sense to duplicate their work: https://github.com/dandavison/delta
