### ISSUE TITLE
git-icdiff seems not work for both modified

### ISSUE THREAD

**Issue by xialu4820723** [jeffkaufman/icdiff#135]
1. enter a git project, edit somefile at branch master, `git stash`
2. `git branch dev && git checkout dev`
3. change somefile, than `git tash pop`
![screenshot from 2018-06-18 13-21-36](https://user-images.githubusercontent.com/16009684/41519434-aca20f36-72fa-11e8-9871-ca99cfa70b2c.png)

the following screenshot takes from `git-icdiff`
![screenshot from 2018-06-18 13-22-22](https://user-images.githubusercontent.com/16009684/41519435-acd718d4-72fa-11e8-9f51-6299168c810e.png)

**Comment by augmentedfourth** [comment]
As of #140, git-icdiff should work for any normal git pathspec you would normally pass to `git diff`.

**Comment by augmentedfourth** [comment]
This issue should be closed now that 1.9.4 is released.

**Comment by jeffkaufman** [comment]
Fix released in 1.9.4
