### ISSUE TITLE
Document the ability to use this script as the default git diff external program

### ISSUE THREAD

**Issue by bruno-** [jeffkaufman/icdiff#14]
Hi,
after I saw this can be used as a `difftool` I wanted to try to take it a step further and use `icdiff` as the default program for `git diff`.

Frankly, I wasn't even sure this would be possible and it also took me some time. For those reasons I think it makes sense to document this "process" so others can benefit from:
- knowing it can be done
- save time

Generalized steps are described here: http://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#External-Merge-and-Diff-Tools

Here are the exact steps:
- create a script named `extDiff` on the path and put the following contents in it:

``` bash
#!/bin/sh
[ $# -eq 7 ] && icdiff "$2" "$5"
```
- make the `extDiff` script executable with `chmod +x extDiff`
- make the script the default program for `git diff` with: `git config --global diff.external extDiff`

After this is done, wherever `git` uses the diff view, `icdiff` will be invoked. I'm using this for a day now and it works just fine.

I didn't want to open a pull request bc I don't know where (and if at all) would you prefer to put the instructions (in the readme, wiki, somewhere else..). So if you don't mind, I'd let this to you.

Hope you like the idea and let me know if I can be of any help for getting this "in"!

**Comment by OliverJAsh** [comment]
I've got this working with `git diff`, but not `git add --patch`. Any ideas how to make this work ubiquitously?

**Comment by JoseAlban** [comment]
As of today, after installing it via brew, I aliased the binary coming with `icdiff version 1.7.2`:
`alias gdi="$(brew --prefix icdiff)/bin/git-icdiff $GIT_DIFF_OPTIONS"`
and it works fine, compared against the analogous:
`git diff $GIT_DIFF_OPTIONS`

**Comment by JoseAlban** [comment]
To get the file labels correctly, plus other personally cool features, I have now in my `.gitconfig`:

```
[pager]
         difftool = true
[difftool "icdiff"]
        cmd = icdiff --head=5000 --highlight --line-numbers -L \"$BASE\" -L \"$REMOTE\" \"$LOCAL\" \"$REMOTE\"
```

And I use it like: `git difftool --tool=icdiff`

**Comment by jez** [comment]
@JoseAlban What do the first four lines do? Can they be used independently of the last two lines?

**Comment by JoseAlban** [comment]
@jez exactly! I just couldn't tie it together nicely with `git show` :( but it has by itself an inline diff (surprisingly), which is what I use (although I wish I could do `icdiff` still):
```
git show --word-diff
```

**Comment by jeffkaufman** [comment]
git-icdiff is now part of the default install (and has been for a while)
