### ISSUE TITLE
Bump icdiff version?

### ISSUE THREAD

**Issue by rmldsky** [jeffkaufman/icdiff#142]
I was wondering if ie. merging changes like https://github.com/jeffkaufman/icdiff/pull/139 or https://github.com/jeffkaufman/icdiff/pull/140 to master, should also be released as a minor versions of `icdiff`?

We are stuck on `1.9.3` for two months now while those minor fixes are pretty useful to be released (not only merged). Not sure how `icdiff` release cycle works, so sorry if I suggest something agains it.

Thanks and keep up the great work! 🎉

**Comment by jeffkaufman** [comment]
Done: 2816d81358a1693b86a76a82f29af6df35fab9f0

Thanks for the poke!

**Comment by jeffkaufman** [comment]
(General release cycle is just, there's a bit of overhead for making a release so I don't typically make one right away when a PR goes in, in case other things also come up.)
