### ISSUE TITLE
Please support UTF-8.

### ISSUE THREAD

**Issue by qvjp** [jeffkaufman/icdiff#144]
I have some Chinese comments in my code. icdiff can't work very well. 

<img width="702" alt="screen shot 2018-11-18 at 10 02 03 pm" src="https://user-images.githubusercontent.com/17522949/48673575-a5ce4c00-eb7d-11e8-8244-246d003fde4c.png">

Support UTF-8 please!

**Comment by jeffkaufman** [comment]
Can you try icdiff with python3?

Or pass `--output-encoding=utf8`?
