### ISSUE TITLE
Constantly asking "Launch 'icdiff' [Y/n]"

### ISSUE THREAD

**Issue by gerroon** [jeffkaufman/icdiff#148]
Hi

I am using this line " git difftool --extcmd=icdiff dca3d3ef0ef 3f59bdc1bd0" and it works but it shows a page then asks me " "Launch 'icdiff' [Y/n]"" I press Y then shows me the next page and so on. It cant go up the page only shows the the upcoming page. I am not sure if this is how it is supposed to work

Debian Buster Git 2.19

thanks

**Comment by jeffkaufman** [comment]
That's git's default behavior with an external diff command.  You can turn it off with:

    git config --global difftool.prompt false

See https://stackoverflow.com/questions/7897517/why-does-git-difftool-not-open-the-tool-directly

**Comment by gerroon** [comment]
Thanks but that just made it worse. It loads the diffs page after page automatically,without stopping and I do not get to see the diffs :)

**Comment by jeffkaufman** [comment]
Does `git difftool --extcmd=icdiff  | less -R` do what you want?

(It's not clear to me what behavior you want)
