### ISSUE TITLE
[feature request] let icdiff support scp protocol

### ISSUE THREAD

**Issue by zhangzq** [jeffkaufman/icdiff#149]
Currently, `icdiff` does not support `scp`. When I run 
```
icdiff scp://other_machine//other_file local_file
```

It tells me the `scp://other_machine//other_file` doestn't exist.

However, `vimdiff scp://other_machine//other_file local_file` works. Can `icdiff` behavior like `vimdiff`?

**Comment by jeffkaufman** [comment]
So, `vimdiff` is more or less `vim`, and so can do a ton of things that it doesn't make sense for other programs to add.

But unix is great for composition, so you can do this!  Just write it as:

    icdiff <(scp other_machine:other_file /dev/stdout) local_file
