### ISSUE TITLE
Diff doesn't seem sensible for block text like a hexdump

### ISSUE THREAD

**Issue by jberryman** [jeffkaufman/icdiff#151]
It seems the diff algorithm falls over a bit when I try to run it on two hexdumps

![hexdiff](https://user-images.githubusercontent.com/210815/51217183-1b903300-18f5-11e9-817f-1f8a07612042.png)

I suppose what I expected to see would be entirely yellow in both panes.

**Comment by jeffkaufman** [comment]
`icdiff` wraps python's `difflib`, so you could report this as a `difflib` issue?

Diffing is hard, though, and I'd be surprised if there are reasonable changes you could make to `difflib` that would handle this case as pure replacement without having it recognize and special-case hex dumps.

**Comment by jberryman** [comment]
Ah, sorry about that. (This seems like it should be the trivial case for replacement FWIW, but I've never implemented a diff and wouldn't know *shrug). 

Thanks for writing this tool!
