### ISSUE TITLE
Unable to change colors

### ISSUE THREAD

**Issue by jlschiavone** [jeffkaufman/icdiff#152]
I'm trying to change the color that's used for "add" with this command:
```
icdiff --color-map='add:cyan_bold'
```

and I cannot get it to work. When I run that command it just returns the list of available options. What am I doing wrong? I'm in Terminal on Mac OS.

Thanks.

**Comment by jeffkaufman** [comment]
When you set `--color-map=...` that's an option, and it applies to the current command.  So you could do something like:

    icdiff --color-map='add:cyan_bold' old.txt new.txt

and it would use cyan bold to show you the additions.

If you want icdiff to always apply this option you could alias it.  In `bash` you'd put a line like:

    alias icdiff="icdiff --color-map='add:cyan_bold'"

into your `~/.bashrc` or `~/.bash_profile` (I forget which one is used on mac)

**Comment by jlschiavone** [comment]
Ah, I see, thank you. I use icdiff exclusively with git. But this does not seem to work.

```
git icdiff --color-map='add:cyan_bold'
```

Is there a way to achieve what I'm trying?

**Comment by jeffkaufman** [comment]
If you're using `icdiff` with `git` then you can set the git configuration item `icdiff.options`.  See https://github.com/jeffkaufman/icdiff/blob/master/git-icdiff
