### ISSUE TITLE
How to read from pipe

### ISSUE THREAD

**Issue by clehene** [jeffkaufman/icdiff#153]
I'm trying to `command | icdiff file -` but can't figure out how to

**Comment by jeffkaufman** [comment]
Use `/dev/stdin` instead of `-`:

<img width="602" alt="screen shot 2019-02-01 at 1 03 21 pm" src="https://user-images.githubusercontent.com/262566/52140816-cd33a180-2621-11e9-8b29-0b8e3114b46c.png">
