### ISSUE TITLE
Pip comnand would not upgrade to 1.9.5

### ISSUE THREAD

**Issue by zouhair** [jeffkaufman/icdiff#164]
It keeps reinstalling 1.9.4

**Comment by jeffkaufman** [comment]
https://pypi.org/project/icdiff/ doesn't have 1.9.5 yet, sorry

@vnitinv?

**Comment by sergekir** [comment]
Are there any plans on upgrading package version at PyPi? Currently pip installs 1.9.1 :(

**Comment by shakefu** [comment]
Hit this as well. Did this project lose access to its PyPI repo?

**Comment by jeffkaufman** [comment]
fixed!
