### ISSUE TITLE
Test assumes to be run in icdiff git repo

### ISSUE THREAD

**Issue by Ikke** [jeffkaufman/icdiff#166]
The test

    check_git_diff gitdiff-only-newlines.txt 4e86205629~1 4e86205629

assumes that it's run in the icdiff git repository, which is not always the case. It assumes a repository to already exist, sets configuration options, and refers to certain commits.

I'm maintaining icdiff for Alpine Linux, where the project is part of the aports repository, and we build from source archives. In those circumstances, the current git repo is aports, not icdiff, which it then also modifies (git config). The tests obviously fails.

It would be better to create a small repository with known contents and run the tests in there (similar how git tests itself).

Another issue is that it runs `git difftool --extcmd icdiff` before exporting `pwd` to `PATH`, causing the command to fail.

**Comment by jeffkaufman** [comment]
Fixed in be1b6d9031ccf5daa3cea55c25b466e353378069
