### ISSUE TITLE
The color is not reset between the line?

### ISSUE THREAD

**Issue by bangzek** [jeffkaufman/icdiff#176]
Is it me or the color is not reset between the line?

![screenshot](https://user-images.githubusercontent.com/5100725/91046393-8a418080-e642-11ea-9d77-a4bf9cbad3c4.png)

**Comment by bangzek** [comment]
Feel free to use these as test case:

[json.txt](https://github.com/jeffkaufman/icdiff/files/5117870/json.txt)
[cbor.txt](https://github.com/jeffkaufman/icdiff/files/5117871/cbor.txt)

**Comment by bjorn3** [comment]
What is exactly the problem? I don't see anything strange.

**Comment by jeffkaufman** [comment]
Could you upload a version of your screenshot with an arrow or circle showing the part you think is wrong?

**Comment by bangzek** [comment]
So my normies expectation is to have the color on line containing:
- delivery_1
- delivery_2
- delivery_4
- delivery_5
to start coloring on number 16 at the left and 9 at the right.

**Comment by bjorn3** [comment]
I am not familiar with the code, but I think `difflib._mdiff` returned those lines as delete + insert instead of changed. Likely because a big part of the line is changed.

**Comment by jeffkaufman** [comment]
Thanks bangzek!  I think bjorn3 Is correct: the underlying diffing library icdiff is using is not able to handle the level of change on those lines.
