### ISSUE TITLE
It doesn't work on svn

### ISSUE THREAD

**Issue by wordfeng** [jeffkaufman/icdiff#179]
![image](https://user-images.githubusercontent.com/25249417/98459147-ebeda180-21d2-11eb-8cc4-d60d58844c7f.png)
![image](https://user-images.githubusercontent.com/25249417/98459168-1fc8c700-21d3-11eb-97a0-e04d3c84fc1b.png)

**Comment by wordfeng** [comment]
![image](https://user-images.githubusercontent.com/25249417/98459409-91097980-21d5-11eb-8b7c-21bb27c7430a.png)
on git is alright

**Comment by jeffkaufman** [comment]
I wonder if perhaps you need to set `--encoding` or `--output-encoding`? They both default to UTF-8.

**Comment by jeffkaufman** [comment]
Also, are you using python2 or python3?  If python2, switching to python3 may help.

**Comment by wordfeng** [comment]
I use another now
