### ISSUE TITLE
Diff on those two files shows that all the line has changed.  Does not get granular to the character.

### ISSUE THREAD

**Issue by deragon** [jeffkaufman/icdiff#181]
Using the code of _icdiff_ from this repository, branch _master_, as of 2021-02-18, the following occurs:

![image](https://user-images.githubusercontent.com/7698377/108363046-7aa28f00-71c2-11eb-923b-d8f49fa622ed.png)

As you notice, the whole line is shown as changed while actually, only some characters have.  Here is what _vimdiff_ shows:

![image](https://user-images.githubusercontent.com/7698377/108363333-cce3b000-71c2-11eb-9e5f-812e5060dcfa.png)

Same output with _meld_.  Thus everything suggest that the problem is with _icdiff_ and not the files.

Command used (click on the files below to download them):

icdiff [filea.txt](https://github.com/jeffkaufman/icdiff/files/6003096/filea.txt) [fileb.txt](https://github.com/jeffkaufman/icdiff/files/6003097/fileb.txt)

**Comment by jeffkaufman** [comment]
icdiff is a wrapper around python's difflib.  You could report this to python if you wanted, but unfortunately this isn't the kind of thing icdiff can fix.
