### ISSUE TITLE
Failed running because it can't find /usr/bin/python on RHEL 8

### ISSUE THREAD

**Issue by satsuyanshen** [jeffkaufman/icdiff#182]
I am trying to run git icdiff on Red Hat 8. However, as is known to all, the default /usr/bin/python is removed. User has to specifically specify python2 or python3. As a result, the icdiff doesn't work on RHEL 8. I didn't see an option that can specify the python path.

**Comment by jeffkaufman** [comment]
Fixed in c6b71aef0b2abdbdfe512cdbcbace6ac6f3a8370
