### ISSUE TITLE
Apt package?

### ISSUE THREAD

**Issue by lonix1** [jeffkaufman/icdiff#185]
Is there an APT version, or a PPA? (for debian/ubuntu)

**Comment by ComedyTomedy** [comment]
It's in ubuntu's universe repo. My `/etc/apt/sources.list` contains the line

    deb http://gb.archive.ubuntu.com/ubuntu/ groovy main restricted universe multiverse

seems to be in Debian too

**Comment by jeffkaufman** [comment]
Yes: `sudo apt install icdiff` works fine for me on Ubuntu.
