### ISSUE TITLE
update icdiff on pypi.org to latest version

### ISSUE THREAD

**Issue by morgana2313** [jeffkaufman/icdiff#186]
Hello,

pypi.org still has the 1.9.1 version from 2017. Do you know how this can be updated?

Regards, Jasper

PS: I love your tool!

**Comment by jeffkaufman** [comment]
Unfortunately, the pypi maintainer is not active.  I'm trying to get it transferred to me: https://github.com/pypa/pypi-support/issues/938

**Comment by jeffkaufman** [comment]
done!
