### ISSUE TITLE
Bug report: configuration for `git icdiff` did not work

### ISSUE THREAD

**Issue by stark-zhang** [jeffkaufman/icdiff#189]
my developing env:
+ `CentOS 7`
+ `git 2.29.2`
+ the latest version of `icdiff` from `pip3`

this is my configuration:
![Uploading 屏幕截图 2021-07-16 162106.png…]()

but after `git icdiff` execute, the output of it has no line numbers or highlights either. any suggestions?

**Comment by jeffkaufman** [comment]
The version on pypi was out of date.  It's been updated now. I think that should fix your issue?

**Comment by stark-zhang** [comment]
> The version on pypi was out of date. It's been updated now. I think that should fix your issue?

I will take a try, thank you.
