### ISSUE TITLE
installing the latest release-2.0.0 requires different command than install instructions

### ISSUE THREAD

**Issue by kevbroch** [jeffkaufman/icdiff#190]
The state of master branch TOT is at 1.9.4: https://github.com/jeffkaufman/icdiff/blob/master/icdiff#L26
But the latest release is at `release-2.0.0`

So the instructions at https://github.com/jeffkaufman/icdiff/blob/master/README.md#installation

states: `  pip install git+https://github.com/jeffkaufman/icdiff.git`

But one needs to do this to get 2.0.0:   `$ pip3 install git+https://github.com/jeffkaufman/icdiff.git@release-2.0.0`

Does this mean the official release is still 1.9.4?

**Comment by bjorn3** [comment]
The only new commit on the 2.0.0 release tag is https://github.com/jeffkaufman/icdiff/commit/f01816fd203f4a30b21b29a758aca8ad2f7ca004 which adds a changelog entry and updates the version in the source code. Other than that the master branch is actually newer.

**Comment by jeffkaufman** [comment]
Looks like I forgot to push `master` after releasing 2.0.0, and then later accepted a PR.  Sorry!

Released 2.0.1 with that PR merged, so `master` is now fully up to date.
