### ISSUE TITLE
icdiff doesn't work on windows

### ISSUE THREAD

**Issue by hao-lee** [jeffkaufman/icdiff#192]
when comparing two simple text files using `git difftool --extcmd=icdiff`. icdiff uses 25% CPU and its memory usage will increase infinitely.

**Comment by jeffkaufman** [comment]
What happens if you run `icdiff` directly on those two files?

**Comment by hao-lee** [comment]
@jeffkaufman hello, 

> What happens if you run icdiff directly on those two files?

Still have problem.

```
$ echo "abc" > 1
$ echo "acd" > 2
$ icdiff 1 2
```

It seems that this problem is related to Git Bash for windows. `icdiff 1 2` works well in  `cmd`  although color scheme is broken.
