### ISSUE TITLE
It seems have some problem about utf-8

### ISSUE THREAD

**Issue by Anopia** [jeffkaufman/icdiff#201]
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/20596060/191164089-1d8c8760-0853-4e58-8512-30fa989114a1.png">

I'm change chinese text in my project
The firsline just change the text in blue box.
And secondline didn't change : ', '',   ,but it highlights.

**Comment by jeffkaufman** [comment]
Can you provide the specific files?

Jeff
