### ISSUE TITLE
Not clear how to install icdiff

### ISSUE THREAD

**Issue by vn971** [jeffkaufman/icdiff#214]
Hi! It's not entirely clear what the "default" installation method of icdiff is.
In README.md, the project says:
> Download the [latest](https://github.com/jeffkaufman/icdiff/releases) icdiff binary and put it on your PATH.

However, there are 2 problems with that:
1. The referenced Releases page doesn't actually have any releases. If I go to Tags, it becomes a different URL.
2. If I open the latest tag, such as [2.0.6](https://github.com/jeffkaufman/icdiff/releases/tag/release-2.0.6), then I don't see any attached binaries. I only the source code. I understand that python files can also be executable, but they're not binaries still. Does the current README mean the main python file `icdiff` when it says "binary"? Or is it something different?

Thank you!

**Comment by jeffkaufman** [comment]
Thanks!  I've fixed the README:

* Point to tags not releases
* It's not a binary; we just want to point people to the `icdiff` in the release
* Add more packaging tool commands

**Comment by vn971** [comment]
@jeffkaufman thank you! :blue_heart: It's pretty neat now I'd say :)
