### ISSUE TITLE
Installation via pip

### ISSUE THREAD

**Issue by nikolay** [jeffkaufman/icdiff#40]
It would be nice to upload icdiff to PyPI for easier installation on Linux.

**Comment by nikolay** [comment]
@yprez Yeah, that's how I use it for now, but would still be better to upload to PyPI.

**Comment by IvanMalison** [comment]
+1

**Comment by alaindomissy** [comment]
+1

**Comment by amirouche** [comment]
:+1:

**Comment by vnitinv** [comment]
@nikolay If you are fine I can take initiative to upload it to PyPI. Even though I will be uploading it you only will be seen as the owner out there as it fetch details from setup.py

**Comment by albfan** [comment]
Why this is still open? https://pypi.python.org/pypi/icdiff

**Comment by nikolay** [comment]
@albfan @jeffkaufman Because it's outdated: current version is 1.9, not 1.8.6, and that is not published by @jeffkaufman, i.e. it's risky to be used.

**Comment by albfan** [comment]
@nikolay better then to close this (as was already done) and open another issue to upgrade pip. no?

**Comment by nikolay** [comment]
@albfan Not really! We have no idea who's published that (user `vnitinv`). Advising people to use untrusted code is a bad advice! Especially when they have published a version that's not official, i.e. v1.8.6, not present in the releases' list here!

I know you guys really love to close issues and move over, this pseudo-agile mentality, in this case, can hurt people.

**Comment by albfan** [comment]
So you want an upgrade issue and a sign pipy module issue.

Only meta issues with lot of goals can hurt, everything else can be splitted to simple tasks. If maintainer sees this issue closed why you don't see it the same way? publish to pipy is done, issues are related of what you ask for, not about all you think "install via pip" means.

Note: For a possible trust pipy issue: https://security.stackexchange.com/questions/79326/which-security-measures-does-pypi-and-similar-third-party-software-repositories. seems pipy is untrusted by default so nothing prevents a user on pipy to get a name like this maintainer.

@vnitinv Can you upgrade pipy to 1.9.0?

**Comment by vnitinv** [comment]
@albfan it's pending from my end only. Will be done by this weekend.
