### ISSUE TITLE
Clarify significance of left_file/right_file argument ordering

### ISSUE THREAD

**Issue by jmitchell** [jeffkaufman/icdiff#41]
The order of the filename arguments is significant, but it's not documented. None of the existing tests demonstrate expected output when the file names are swapped.

Consider these two files: [StackTest.cmp](https://gist.github.com/jmitchell/bd5e78e7c8409b612a36) and [StackTest.out](https://gist.github.com/jmitchell/0430191c3196f4549dd3)

Whether the `--whole-file` option is enabled or not, `icdiff StackTest.cmp StackTest.out` fails to indicate `StackTest.cmp` has two more lines than `StackTest.out`. Diffs between line 2 in both files are highlighted in yellow.

When I swap the filename args (`icdiff StackTest.out StackTest.cmp`) it's clear one file has two more lines than the other. However, now all the yellow highlights on line 2 have been replaced by whole-line red/green.

Is there a way to get all this information in a single run?

**Comment by jeffkaufman** [comment]
This looks like a `difflib` issue (icdiff is just a console wrapper around difflib)

```
>>> print(''.join(difflib.context_diff(open("StackTest.out").read(), open("StackTest.cmp").read())))
*** 
--- 
***************
*** 73,136 ****
        2! 5  9!  !  ! |!  !  !  !  !  !  ! -! 1!  !  ! |!  !  !  !  !  !  !  ! 0!  !  ! |!  !  !  !  !  ! -! 9! 1!  !  ! |!  !  !  !  !  !  ! 8! 2!  !  ! |!  !  !  !  !  ! 1! 1! 2!  !  ! |! 
--- 73,250 ----
        2! 6! 6!  !  ! |!  !  !  !  !  !  ! -! 1!  !  ! |!  !  !  !  !  !  !  ! 0!  !  ! |!  !  !  !  !  !  !  ! 0!  !  ! |!  !  !  !  !  !  !  ! 0!  !  ! |!  !  !  !  !  !  ! -! 1!  !  ! |! 
! |!  ! R! A! M! [! 2! 6! 1! ]!  ! |!  ! R! A! M! [! 2! 6! 2! ]!  ! |!  ! R! A! M! [! 2! 6! 3! ]!  ! |!  ! R! A! M! [! 2! 6! 4! ]!  ! |!  ! R! A! M! [! 2! 6! 5! ]!  ! |! 
! |!  !  !  !  !  !  !  ! 0!  !  ! |!  !  !  !  !  !  ! -! 1!  !  ! |!  !  !  !  !  !  !  ! 0!  !  ! |!  !  !  !  !  !  !  ! 0!  !  ! |!  !  !  !  !  ! -  9! 1!  !  ! |! 

>>> print(''.join(difflib.context_diff(open("StackTest.cmp").read(), open("StackTest.out").read())))
*** 
--- 
***************
*** 73,80 ****
        2! 6! 6        |--- 73,80 ----
        2! 5! 9        |***************
*** 105,215 ****
         -  -  - 0-  -  - |-  -  -  -  -  -  -  - 0-  -  - |-  -  -  -  -  -    -! 1!  !  ! |! 
! |!  ! R! A! M! [! 2! 6! 1! ]!  ! |!  ! R! A! M! [! 2! 6! 2! ]!  ! |!  ! R! A! M! [! 2! 6! 3! ]!  ! |!  ! R! A! M! [! 2! 6! 4! ]!  ! |!  ! R! A! M! [! 2! 6! 5! ]!  ! |! 
! |!  !  !  !  !  !  !  ! 0!  !  ! |!  !  !  !  !  !  ! -  1      --- 105,112 ----
           -! 9  1      ***************
*** 220,227 ****
         !  ! 0        |--- 117,124 ----
         ! 8! 2        |***************
*** 230,249 ****
         -  -  - 0-  -  - |-  -  -  -  -  - -- 9  1        |--- 127,135 ----
           1+ 1+ 2        |
```

You don't have to understand what a context diff is supposed to be in order to see that these are pretty different outputs.
