### ISSUE TITLE
Importing icdiff module to my python code is giving error

### ISSUE THREAD

**Issue by Jainpriyal** [jeffkaufman/icdiff#46]
Hi,

I have installed icdiff in Mac, its working fine from terminal. But when I am importing it in my python code it is giving error.
   ```
ImportError: No module named icdiff
```

How to import this module, is it not supported ??

**Comment by jeffkaufman** [comment]
The easiest way to import `icdiff` is to add it's containing directory to `sys.path`:

    import sys
    sys.path.append("/containing/directory ")
    import icdiff

**Comment by vnitinv** [comment]
for what you said, icdiff need to be a .py file. Then only it can be imported. 

nitinkr-mba13:ex nitinkr$ which icdiff
/Library/Frameworks/Python.framework/Versions/2.7/bin/icdiff
nitinkr-mba13:ex nitinkr$ python
Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append(r'/Library/Frameworks/Python.framework/Versions/2.7/bin')
>>> import icdiff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named icdiff

**Comment by jeffkaufman** [comment]
That's fine: rename or symlink it to `icdiff.py`.

**Comment by jeffkaufman** [comment]
Also, depending on what you're trying to do, consider Python's built in Difflib.
