### ISSUE TITLE
exit code 1 if there is difference

### ISSUE THREAD

**Issue by dashed** [jeffkaufman/icdiff#47]
> DIAGNOSTICS
> 
> ```
>   An  exit status of 0 means no differences were found, 1 means some dif-
>   ferences were found, and 2 means trouble.
> ```

http://unixhelp.ed.ac.uk/CGI/man-cgi?diff
http://stackoverflow.com/questions/6971284/what-are-the-error-exit-values-for-diff

**Comment by jeffkaufman** [comment]
`icdiff` isn't intended for scripting, because I don't want to make commitments about what the output will look like.

What do you want to use this for?
