### ISSUE TITLE
icdiff 1.7.3 reports 1.7.2 version

### ISSUE THREAD

**Issue by gpakosz** [jeffkaufman/icdiff#52]
Not a big one, but after having installed `1.7.3`, `icdiff --version` reports `icdiff version 1.7.2`.

[See source code](https://github.com/jeffkaufman/icdiff/blob/fc4e100b855ecfed8f885e5119bc7218f810830e/icdiff#L22).

**Comment by nikolay** [comment]
@jeffkaufman I confirm, too.
