### ISSUE TITLE
Solarized Dark iTerm Colors for changes grey

### ISSUE THREAD

**Issue by Anzumana** [jeffkaufman/icdiff#54]
Changes are being displayed in grey.
What would be the preferred way of defining what colors icdiff uses based on the current selected colorscheme ?

**Comment by jeffkaufman** [comment]
How does it look with `--no-bold`?

```
  --no-bold             use non-bold colors; recommended for with solarized
```

**Comment by Anzumana** [comment]
![screen shot 2015-08-28 at 16 03 43](https://cloud.githubusercontent.com/assets/2629041/9548062/82af2350-4d9e-11e5-8889-d2cb3aad2d94.png)

**Comment by Anzumana** [comment]
in the file above i only changed some color values

**Comment by jeffkaufman** [comment]
Could you run this script to give you a table of available colors: http://askubuntu.com/a/27318

Are there ones on that list that would look good here?

**Comment by Anzumana** [comment]
cool script. first of thanks for that :)
0;35;40
seems pretty cool to me ( at for changes )

**Comment by Anzumana** [comment]
![screen shot 2015-08-28 at 17 22 49](https://cloud.githubusercontent.com/assets/2629041/9550067/718ae932-4da9-11e5-8cfa-539a8d268e70.png)

**Comment by Anzumana** [comment]
How do i change icdiff to that color?

**Comment by jeffkaufman** [comment]
Looking at the `color_codes` table in `icdiff` we can see `0;35` corresponds to `magenta`.  

So look down to the `colorize` function in `icdiff` and replace the value for `C_CHG` (the color to display changes in, default yellow) with `color_codes["magenta"]`.

**Comment by jeffkaufman** [comment]
It's now possible to do this with `--color-map=change:magenta`: 1bcc61b417a37be8af78344469438937af1b4ef8

This isn't in a released version yet, but it will be in the next version after 1.9.1.
