### ISSUE TITLE
Feature request: exclude files matching a pattern

### ISSUE THREAD

**Issue by xpe** [jeffkaufman/icdiff#60]
Would you be open to adding the ability to exclude a pattern?

For example, from diff on OS X:

```
-x PAT  --exclude=PAT
              Exclude files that match PAT.
```

This is useful to diff two folders while excluding, for example, the `.git` subdirectory.

**Comment by gitressa** [comment]
I agree, this would be a great feature. I just had the exact same issue with a `.git` folder.
