### ISSUE TITLE
Take standard input

### ISSUE THREAD

**Issue by geowa4** [jeffkaufman/icdiff#64]
When making changes to a file in Vim, I find myself wanting to see what changes I have made in my buffer. One way to to this is `:w !diff % -` where `%` is the name of the current file and `-` is the contents of the current buffer passed in via standard input. Currently, `icdiff` requires both to be a file.

**Comment by edentsai** [comment]
I have same problem, for example:

1. diff 2 standard output with icdiff v1.7.2
```
$ icdiff --version
icdiff version 1.7.2
$ icdiff <(ls -1 ~/) <(ls -1 -a ~/ )
# this can work
```

2. Changed to latest icdiff v1.8.1, I can't diff 2 standard output
```
$ icdiff --version
icdiff version 1.8.1
$ icdiff <(ls -1 ~/) <(ls -1 -a ~/ )
# No any response
```

**Comment by edentsai** [comment]
I finger out [this commit 78938d33567c8c73c3539e2168a6862de21d58e1](https://github.com/jeffkaufman/icdiff/commit/78938d33567c8c73c3539e2168a6862de21d58e1#diff-6efeae13c3a17fdab570aaba05da8b65L514) cause diff 2 standard outputs disabled.

The original `diff_files()` can diff 2 standard outputs

**Comment by jeffkaufman** [comment]
Fixed in https://github.com/jeffkaufman/icdiff/pull/88 , which is in 1.9.x
