### ISSUE TITLE
Clarify copyrights

### ISSUE THREAD

**Issue by satta** [jeffkaufman/icdiff#68]
Hi,

I am packaging icdiff for Debian and I am looking to sort out some minor licensing issues.
The Python license linked by you in README.md specifies that the Python copyright:
```
Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006 Python Software Foundation; All Rights Reserved
```
must be retained in derivative based on it (section 2). This is missing in the script header. Also, section 3 states that

> In the event Licensee prepares a derivative work that is based on
> or incorporates Python or any part thereof, and wants to make
> the derivative work available to others as provided herein, then
> Licensee hereby agrees to include in any such work a brief summary of
> the changes made to Python.

It would be nice to have such a brief summary.

Also, the UTF-8 decoder capability and stress test file (`tests/b/1` and `tests/input-3.txt`) seems like it was not prepared by you but by Markus Kuhn. The version of the file you are distributing with icdiff does not include any license information, but a newer version does (https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt, CC-BY). It would be nice to have this file updated or the license specified by you.

**Comment by jeffkaufman** [comment]
Added, with cdede392b6c886e912be8819ee17cddea9c3b679, and released as 1.7.6.

**Comment by satta** [comment]
Excellent, thanks! I wonder if you could also update the test files so they also contain a copyright. See my original comment above.

**Comment by jeffkaufman** [comment]
All test files except input-3 (which you fixed) are trivial; do you really think it's worth it?

**Comment by satta** [comment]
The problem is that in Debian we need to be able to prove that a given file is under a free license, and that is only possible in the newer version of the UTF8 file (`input-3.txt` and `tests/b/1`) I added in #70 as only this one has 'CC-BY' explicitly mentioned in the text.
Please note that with your commit the file 440de77ff674c4c6f5c31ab445983c8cc29fab8b the file `tests/b/1` is still the old one without the license notice. This will still impede redistribution.
The rest of the changes in #70 was necessary to keep the tests passing as the new UTF8 file is slightly different than the previous one. I did a `--regold` to update the reference output. I hope that was OK.

**Comment by jeffkaufman** [comment]
Sorry, I've fixed `tests/b/1` and regolded.  Version 1.8.1 should be what you want.

**Comment by satta** [comment]
That was quick, many thanks! Unfortunately, there's one thing left: I now run into the problem described by #73 and #75. I suggest you separate the `icdiff` tool from the module to be loaded so you do not have to rename the tool to `icdiff.py` -- globally available commands with script extensions are discouraged in Debian and I would have to work around it. Also, there are good arguments for not doing so (https://wiki.debian.org/UpstreamGuide#Language_extensions_in_scripts).
That indeed seems to be the last remaining request :)

**Comment by xrat** [comment]
Great work, guys! Looking forward to seeing icdiff packaged for Debian. Thanks a lot.

**Comment by satta** [comment]
Regarding my last comment, please also see PR #79.

**Comment by satta** [comment]
Just for the record, I would be really happy to see #75 merged as it is a better solution than my proposal. That would get me going again for finishing up the packaging.

**Comment by jeffkaufman** [comment]
The problem with #75 is the same as #79: I want to still have a `icdiff` on your `PATH` as `icdiff` and not `icdiff.py` but I also want to provide a simple copy-paste install for people who want that.

**Comment by satta** [comment]
Ah, I see and I do understand that. I was just asking because in the current 1.8.1 the `setup.py` is broken due to #72, so I won't be able to package this without either locally reverting the module functionality (commit 46d5a721265112c3b38afd71f84bb9bc7ad74a92) or applying #75 to the Debian version. Since I usually like to stick with the original upstream I was looking for a way to sort it out...
Does anyone possibly have other suggestions?
