### ISSUE TITLE
pip install instructions don't work

### ISSUE THREAD

**Issue by lurch** [jeffkaufman/icdiff#72]
``` bash
$ pip install git+https://github.com/jeffkaufman/icdiff.git
Collecting git+https://github.com/jeffkaufman/icdiff.git
  Cloning https://github.com/jeffkaufman/icdiff.git to /tmp/pip-430nkex7-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-430nkex7-build/setup.py", line 3, in <module>
        from icdiff import __version__
    ImportError: No module named 'icdiff'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-430nkex7-build/
```

I wonder if this might be because you forgot to rename `icdiff` to `icdiff.py` when merging #69 ?
https://github.com/jeffkaufman/icdiff/commit/46d5a721265112c3b38afd71f84bb9bc7ad74a92

**Comment by xuedong09** [comment]
+1
 Fix ` ImportError: No module named icdiff` #73 

This pull request fix my problem

**Comment by satta** [comment]
I'd suggest not to rename the main command to `icdiff.py` without also providing at least wrapper script without the extension. The best solution here would be IMHO a proper separation between the module code and the tool itself. The module would have the .py extension and live in the proper Python library paths, and the tool without the extension would just use the module and live in `/usr/bin`.

**Comment by lodagro** [comment]
Just tried to install icdiff using the above ```pip``` command and got the same error. 

```python
Collecting git+https://github.com/jeffkaufman/icdiff.git
  Cloning https://github.com/jeffkaufman/icdiff.git to /tmp/pip-BAZU13-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-BAZU13-build/setup.py", line 3, in <module>
        from icdiff import __version__
    ImportError: No module named icdiff
```

As workaround i did

```
cd /tmp/pip-BAZU13-build
ln -s icdiff icdiff.py
python setup.py install
```

Install went fine, both module and _binary_ available (which is what i want).

**Comment by jeffkaufman** [comment]
This was resolved several months ago; I think it's all set now.
