### ISSUE TITLE
Feature request: support to read diff file with icdiff

### ISSUE THREAD

**Issue by tobegit3hub** [jeffkaufman/icdiff#77]
`icdiff` is awesome to compare with two files and be used with git.

Sometimes we just get the diff file and it would be much better to use `icdiff` to read that diff file.

**Comment by jeffkaufman** [comment]
This seems hard, and not a good fit for how icdiff currently works internally.  Sorry!

**Comment by tobegit3hub** [comment]
Well. Thanks @jeffkaufman anyway.
