### ISSUE TITLE
GH Repo version behind with PyPi

### ISSUE THREAD

**Issue by micahcochran** [jeffkaufman/icdiff#82]
It seems like the PyPi version is at version 1.8.5.

Github seems to be at version 1.8.1.  Why is the github repo. behind the PyPi release?

I used meld (a competing diff utility) to compare the two icdiff files and there are about 20 lines that have changed.

**Comment by vnitinv** [comment]
@micahcochran Will be is sync once pull request #75 is merged. 

https://github.com/jeffkaufman/icdiff/pull/75/files

**Comment by peanball** [comment]
The PyPi version is broken with --recursive. Please fix #75 before attempting to merge anything!

**Comment by jeffkaufman** [comment]
The version on PyPI is now 1.9.1, so this is all set now (and has been for a while).

> why do you publish something on PyPi in Jeff's name?

On PyPI I see:

```
Author: Jeff Kaufman
Home Page: http://www.jefftk.com/icdiff
Package Index Owner: vnitinv
```

Which looks right to me! It's saying that I wrote this, and @vnitinv handles packaging this for PyPI (thanks!)

**Comment by vnitinv** [comment]
@jeffkaufman I will check if I can transfer the ownership on PyPI to you only. I understand many people may ask the same question as done by @micahcochran 

@jeffkaufman, please share me the username for PyPI.

**Comment by jeffkaufman** [comment]
@vnitinv I'm happy for you to continue as the PyPI packager if you're up for that.  It's very useful for you to be doing it!
