### ISSUE TITLE
Create new release and update homebrew-core Formula

### ISSUE THREAD

**Issue by stgarf** [jeffkaufman/icdiff#87]
Please tag a 1.8.2 release and update homebrew-core
[icdiff.rb](../../../Homebrew/homebrew-core/blob/master/Formula/icdiff.rb)

Thanks @jeffkaufman

**Comment by jeffkaufman** [comment]
Looks like this is fixed now: https://github.com/Homebrew/homebrew-core/blob/master/Formula/icdiff.rb
