### ISSUE TITLE
Unable to diff named pipes

### ISSUE THREAD

**Issue by bddppq** [jeffkaufman/icdiff#89]
Sometimes it's useful to diff output of two commands (without first storing the output into a temporary file), e.g

```shell
icdiff <(echo 1) <(echo 2)
```

Right now icdiff will ignore and exit without any outputs or error messages if any one of the (two) arguments is irregular file, since it uses `os.path.isfile` and `os.path.isdir` to determine whether the argument is a file or a directory. But for named pipes (actually any irregular files) both functions return False. I suggest changing the logic to only test whether an argument is a directory, and treat all other cases as readable files.

**Comment by edentsai** [comment]
- https://github.com/jeffkaufman/icdiff/pull/88
- https://github.com/jeffkaufman/icdiff/pull/81

**Comment by albfan** [comment]
I think this should work by now
